name: my_dog_app_final
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  gallery_saver: any
  path_provider: any
  # for design
  cupertino_icons: ^1.0.2

  # connect network
  http: ^0.13.4
  http_interceptor: ^1.0.2
  connectivity_plus: any
  share_plus: any

  # database
  hive_flutter: ^1.1.0

  # image
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+3

  # decoration
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

